const devicedata = [
  {
    count: 1,
    next: null,
    previous: null,
    results: [
      {
        id: 19,
        url: "https://netbox.kiewit.com/api/dcim/devices/19/",
        display: "KOSTXINGRWA01",
        name: "KOSTXINGRWA01",
        device_type: {
          id: 3,
          url: "https://netbox.kiewit.com/api/dcim/device-types/3/",
          display: "SRX380",
          manufacturer: {
            id: 2,
            url: "https://netbox.kiewit.com/api/dcim/manufacturers/2/",
            display: "Juniper",
            name: "Juniper",
            slug: "juniper",
          },
          model: "SRX380",
          slug: "srx380",
        },
        device_role: {
          id: 6,
          url: "https://netbox.kiewit.com/api/dcim/device-roles/6/",
          display: "ROUTER_WAN",
          name: "ROUTER_WAN",
          slug: "router_wan",
        },
        tenant: null,
        platform: null,
        serial: "",
        asset_tag: null,
        site: {
          id: 1,
          url: "https://netbox.kiewit.com/api/dcim/sites/1/",
          display: "KOSTXING",
          name: "KOSTXING",
          slug: "kostxing",
        },
        location: {
          id: 54,
          url: "https://netbox.kiewit.com/api/dcim/locations/54/",
          display: "SKILLS_CENTER_MDF",
          name: "SKILLS_CENTER_MDF",
          slug: "skills_center_mdf",
          _depth: 1,
        },
        rack: {
          id: 2,
          url: "https://netbox.kiewit.com/api/dcim/racks/2/",
          display: "A1",
          name: "A1",
        },
        position: 20,
        face: {
          value: "front",
          label: "Front",
        },
        parent_device: null,
        status: {
          value: "active",
          label: "Active",
        },
        airflow: {
          value: "front-to-rear",
          label: "Front to rear",
        },
        primary_ip: null,
        primary_ip4: null,
        primary_ip6: null,
        cluster: null,
        virtual_chassis: null,
        vc_position: null,
        vc_priority: null,
        description: "",
        comments: "",
        local_context_data: null,
        tags: [],
        custom_fields: {
          POLLING: null,
          ALERT: null,
        },
        config_context: {},
        created: "2023-04-12T22:41:06.507867Z",
        last_updated: "2023-04-18T19:25:53.160201Z",
      },
    ],
  },
];

export default devicedata;
